# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011a9f90e95082415274099ca02f631fdc676515d457da7af3ecc135c7529e0bdd1ed798bc8c1ecac20752c4538b1a31f3bb209f77b72fc81e22fabf0436c3f6

test:
  secret_key_base: bea8ac54a5d7fa0d84a93ed615531ce8f56f6b269cad694aa28259f1b6fcae11d2639d5d4ce5b7f8949d0d75e738743b768b9a259ccd1077297daa2be318ba5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
